blueprint:
  name: ZEN32 LED state -- merged
  description: For Zooz ZEN32. Sets the indicator color when linked entities are off, on or unavailable.  4.2024.42
  domain: automation
  input:
    zooz_switch:
      name: Zooz Switch
      description: List of available Zooz ZEN32 switches.
      selector:
        device:
          filter:
            - integration: zwave_js
              manufacturer: Zooz
              model: ZEN32
            - integration: zwave_js
              manufacturer: Zooz
              model: ZEN32 800LR
          multiple: false
    input_entity0:
      name: Entity for button 0 (Big button)
      description: The entity to track
      selector:
        entity:
          domain:
          - fan
          - light
          - media_player
          - sensor
          - switch
          multiple: false
    off_state0:
      name: Off behavior for button 0
      description: Led state when target is off
      default: Led On
      selector:
        select:
          mode: dropdown
          options:
            - label: Led On
              value: '3'
            - label: Led Off
              value: '2'
    off_color0:
      name: Off color for button 0
      description: Color for led when target is off (default white)
      default: White
      selector:
        select:
          mode: dropdown
          options:
            - label: White
              value: '0'
            - label: Blue
              value: '1'
            - label: Green
              value: '2'
            - label: Red
              value: '3'
            - label: Magenta
              value: '4'
            - label: Yellow
              value: '5'
            - label: Cyan
              value: '6'
    on_state0:
      name: On behavior for button 0
      description: Led state when target is off
      default: Led On
      selector:
        select:
          mode: dropdown
          options:
            - label: Led On
              value: '3'
            - label: Led Off
              value: '2'
    on_color0:
      name: On color for button 0
      description: Color for led when target is on (default white)
      default: Blue
      selector:
        select:
          mode: dropdown
          options:
            - label: White
              value: '0'
            - label: Blue
              value: '1'
            - label: Green
              value: '2'
            - label: Red
              value: '3'
            - label: Magenta
              value: '4'
            - label: Yellow
              value: '5'
            - label: Cyan
              value: '6'
    unavail_state0:
      name: Unavailable State for button 0
      description: Led state when target is unavailable
      default: Led off
      selector:
        select:
          mode: dropdown
          options:
            - label: Led On
              value: '3'
            - label: Led Off
              value: '2'
    unavail_color0:
      name: Unavailable Color for button 0
      description: Color for led when target is unavailable (default red)
      default: Red
      selector:
        select:
          mode: dropdown
          options:
            - label: White
              value: '0'
            - label: Blue
              value: '1'
            - label: Green
              value: '2'
            - label: Red
              value: '3'
            - label: Magenta
              value: '4'
            - label: Yellow
              value: '5'
            - label: Cyan
              value: '6'
    input_entity1:
      name: Entity for button 1 (Top left button)
      description: The entity to track
      selector:
        entity:
          domain:
          - fan
          - light
          - media_player
          - sensor
          - switch
          multiple: false
    off_state1:
      name: Off behavior for button 1
      description: Led state when target is off
      default: Led On
      selector:
        select:
          mode: dropdown
          options:
            - label: Led On
              value: '3'
            - label: Led Off
              value: '2'
    off_color1:
      name: Off color for button 1
      description: Color for led when target is off (default white)
      default: White
      selector:
        select:
          mode: dropdown
          options:
            - label: White
              value: '0'
            - label: Blue
              value: '1'
            - label: Green
              value: '2'
            - label: Red
              value: '3'
            - label: Magenta
              value: '4'
            - label: Yellow
              value: '5'
            - label: Cyan
              value: '6'
    on_state1:
      name: On behavior for button 1
      description: Led state when target is off
      default: Led On
      selector:
        select:
          mode: dropdown
          options:
            - label: Led On
              value: '3'
            - label: Led Off
              value: '2'
    on_color1:
      name: On color for button 1
      description: Color for led when target is on (default white)
      default: Green
      selector:
        select:
          mode: dropdown
          options:
            - label: White
              value: '0'
            - label: Blue
              value: '1'
            - label: Green
              value: '2'
            - label: Red
              value: '3'
            - label: Magenta
              value: '4'
            - label: Yellow
              value: '5'
            - label: Cyan
              value: '6'
    unavail_state1:
      name: Unavailable State for button 1
      description: Led state when target is unavailable
      default: Led off
      selector:
        select:
          mode: dropdown
          options:
            - label: Led On
              value: '3'
            - label: Led Off
              value: '2'
    unavail_color1:
      name: Unavailable Color for button 1
      description: Color for led when target is unavailable (default red)
      default: Red
      selector:
        select:
          mode: dropdown
          options:
            - label: White
              value: '0'
            - label: Blue
              value: '1'
            - label: Green
              value: '2'
            - label: Red
              value: '3'
            - label: Magenta
              value: '4'
            - label: Yellow
              value: '5'
            - label: Cyan
              value: '6'

mode: parallel
max: 5
variables:
  controller_id: !input 'zooz_switch'
  toggle_offset: 1
  color_offset: 6
  target_entity0: !input 'input_entity0'
  target0:
    button_id: 0
    off_state: !input 'off_state0'
    off_color: !input 'off_color0'
    on_state: !input 'on_state0'
    on_color: !input 'on_color0'
    unavail_state: !input 'unavail_state0'
    unavail_color: !input 'unavail_color0'
  target_entity1: !input 'input_entity1'
  target1:
    button_id: 1
    off_state: !input 'off_state1'
    off_color: !input 'off_color1'
    on_state: !input 'on_state1'
    on_color: !input 'on_color1'
    unavail_state: !input 'unavail_state1'
    unavail_color: !input 'unavail_color1'
trigger:
  - alias: DeviceStateTrigger
    platform: state
    entity_id: 
    - !input 'input_entity0'
    - !input 'input_entity1'

action:
  - choose:
    - conditions: '{{ is_state(trigger.entity_id, ''off'') }}' # switch off
      sequence:
        - parallel:
          - service: zwave_js.set_config_parameter # turn indicator on/off
            data:
              parameter: '{{ (target0.button_id | int) + (toggle_offset | int) }}'
              value: '{{ target0.off_state.value }}'
            target: 
              device_id: '{{ controller_id }}'
          - service: zwave_js.set_config_parameter # set indicator color
            data:
              parameter: '{{ (target0.button_id | int) + (color_offset | int) }}'
              value: "{{ target0.off_color.value }}"
            target:
              device_id: '{{ controller_id }}'
    - conditions: '{{ is_state(trigger.entity_id, ''on'') }}' # switch on
      sequence:
        - parallel:
          - service: zwave_js.set_config_parameter # turn indicator on/off
            data:
              parameter: '{{ (target0.button_id | int) + (toggle_offset | int) }}'
              value: "{{ target0.on_state.value }}"
            target: 
              device_id: '{{ controller_id }}'
          - service: zwave_js.set_config_parameter # set indicator color
            data:
              parameter: '{{ (target0.button_id | int) + (color_offset | int) }}'
              value: "{{ target0.on_color.value }}"
            target:
              device_id: '{{ controller_id }}'
    - conditions: '{{ is_state(trigger.entity_id, ''unavailable'') }}' # switch unavailable
      sequence:
        - parallel:
          - service: zwave_js.set_config_parameter # turn indicator on/off
            data:
              parameter: '{{ (target0.button_id | int) + (toggle_offset | int) }}'
              value: '{{ target0.unavail_state.value }}'
            target: 
              device_id: '{{ controller_id }}'
          - service: zwave_js.set_config_parameter # set indicator color
            data:
              parameter: '{{ (target0.button_id | int) + (color_offset | int) }}'
              value: '{{ target0.unavail_color.value }}'
            target:
              device_id: '{{ controller_id }}'